# Generated by Django 6.0.6 on 2026-07-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
