# Generated by Django 6.0.6 on 2026-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projectimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cta_text',
            field=models.TextField(default="Let's build something exceptional together."),
        ),
        migrations.AddField(
            model_name='project',
            name='cta_title',
            field=models.CharField(default='Ready to build your next project?', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
