# Generated by Django 6.0.6 on 2026-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_challenge_project_cta_text_project_cta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cta_tag',
            field=models.CharField(default="LET'S BUILD SOMETHING AMAZING", max_length=100),
        ),
    ]
