# Generated by Django 6.0.6 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


def convert_client_names(apps, schema_editor):

    Project = apps.get_model("portfolio", "Project")
    Client = apps.get_model("clients", "Client")

    try:
        pase_client = Client.objects.get(company="Pase Africa")
    except Client.DoesNotExist:
        return

    for project in Project.objects.all():

        if str(project.client) == "Pase Africa":

            project.client = pase_client.id

            project.save(update_fields=["client"])


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("portfolio", "0004_project_cta_tag"),
    ]

    operations = [

        migrations.RunPython(
            convert_client_names,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="clients.client",
            ),
        ),
    ]